import fs from "fs";
import path from "path";
import { imageSizeFromFile } from "image-size/fromFile";
import GalleryGrid from "./GalleryGrid";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Visual Gallery | I Gusti Ngurah Anom Hariyadi — Dokumentasi Kegiatan & Portofolio Visual",
  description: "Galeri visual dokumentasi perjalanan karir, kegiatan organisasi, kepanitiaan, dan momen penting I Gusti Ngurah Anom Hariyadi (Anom). Menampilkan fotografi, desain grafis, dan momen profesional.",
  openGraph: {
    title: "Visual Gallery — Anom Hariyadi",
    description: "Koleksi foto dokumentasi kegiatan, organisasi, dan portofolio visual.",
  },
};

interface ImageItem {
  src: string;
  thumb: string;
  width: number;
  height: number;
  aspectRatio: number;
  name: string;
}

async function getGalleryImages(): Promise<ImageItem[]> {
  const galleryDir = path.join(process.cwd(), "public", "gallery");
  const thumbsDir = path.join(galleryDir, "thumbs");
  
  // Ensure the directory exists
  if (!fs.existsSync(galleryDir)) {
    try {
      await fs.promises.mkdir(galleryDir, { recursive: true });
    } catch (err) {
      console.error("Failed to create gallery directory:", err);
      return [];
    }
    return [];
  }

  // Check if thumbs manifest exists (generated by compress-gallery.js)
  const manifestPath = path.join(thumbsDir, "manifest.json");
  const hasManifest = fs.existsSync(manifestPath);
  let manifest: Array<{ original: string; thumb: string | null; width: number; height: number; aspectRatio: number }> = [];
  
  if (hasManifest) {
    try {
      manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
    } catch {
      console.warn("Failed to parse gallery manifest, falling back to file scanning");
    }
  }

  // If manifest exists and is populated, use it (fastest path)
  if (manifest.length > 0) {
    return manifest.map((item) => {
      const thumbExists = item.thumb && fs.existsSync(path.join(thumbsDir, item.thumb));
      return {
        src: `/gallery/${item.original}`,
        thumb: thumbExists ? `/gallery/thumbs/${item.thumb}` : `/gallery/${item.original}`,
        width: item.width,
        height: item.height,
        aspectRatio: item.aspectRatio,
        name: item.original,
      };
    });
  }
  
  // Fallback: scan directory manually (no thumbnails available)
  try {
    const files = await fs.promises.readdir(galleryDir);
    const imageExtensions = [".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg", ".bmp"];
    
    const imageFiles = files.filter((file) => {
      const ext = path.extname(file).toLowerCase();
      return imageExtensions.includes(ext);
    });
    
    const images: ImageItem[] = [];
    
    for (const file of imageFiles) {
      const filePath = path.join(galleryDir, file);
      
      // Skip directories
      const stat = await fs.promises.stat(filePath);
      if (stat.isDirectory()) continue;
      
      try {
        // Read file dimensions asynchronously using the modern image-size 2.x fromFile API
        const dimensions = await imageSizeFromFile(filePath);
        const width = dimensions.width || 800;
        const height = dimensions.height || 600;
        
        // Check for matching thumbnail
        const baseName = path.basename(file, path.extname(file));
        const thumbName = `${baseName}.webp`;
        const thumbExists = fs.existsSync(path.join(thumbsDir, thumbName));
        
        images.push({
          src: `/gallery/${file}`,
          thumb: thumbExists ? `/gallery/thumbs/${thumbName}` : `/gallery/${file}`,
          width,
          height,
          aspectRatio: width / height,
          name: file,
        });
      } catch (err) {
        console.error(`Error reading metadata for ${file} with imageSizeFromFile:`, err);
        // Fallback dimensions in case file is corrupt or image-size fails to parse
        images.push({
          src: `/gallery/${file}`,
          thumb: `/gallery/${file}`,
          width: 800,
          height: 600,
          aspectRatio: 800 / 600,
          name: file,
        });
      }
    }
    
    // Sort images alphabetically by file name (so names like pic1, pic2, etc. order cleanly)
    return images.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' }));
  } catch (err) {
    console.error("Error reading gallery files:", err);
    return [];
  }
}

export default async function GalleryPage() {
  const images = await getGalleryImages();
  
  return <GalleryGrid initialImages={images} />;
}
